# Generated by Django 4.2.20 on 2025-05-15 14:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemail',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='simple_mail', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='simplemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simplemailconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simplemailconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='simple_mail', verbose_name='Logo'),
        ),
    ]
